version: "3.4"
services:
  besu.public.dappnode.eth:
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: 22.4.3-SNAPSHOT
    image: "besu.public.dappnode.eth:22.4.3"
    restart: unless-stopped
    volumes:
      - "besu:/besu"
    environment:
      - >-
        EXTRA_OPTIONS=--data-storage-format=BONSAI --sync-mode=X_CHECKPOINT
        --metrics-enabled=true
    ports:
      - "40303"
      - 40303/udp
      - "8545"
      - "9545"
volumes:
  besu: {}
