version: "3.4"
services:
  besu.dappnode.eth:
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: 21.7.3-SNAPSHOT
    image: "besu.dappnode.eth:0.1.0"
    restart: unless-stopped
    volumes:
      - "besu:/besu"
    environment:
      - EXTRA_OPTIONS=--Xdata-storage-format=BONSAI
    ports:
      - "40303"
      - 40303/udp
      - "8545"
volumes:
  besu: {}
