version: "3.4"
services:
  teku.public.dappnode.eth:
    build:
      context: ./build
      args:
        UPSTREAM_VERSION: 21.10.1
    image: "teku.public.dappnode.eth:0.1.2"
    restart: unless-stopped
    volumes:
      - "teku:/teku"
    environment:
      - EXTRA_OPTIONS=--rest-api-enabled=true
    ports:
      - "8008"
      - "9000"
      - "5051"
      - 9000/udp
volumes:
  teku: {}
